WIP - Dynamic botnet.conf

diff --git a/viperbot b/viperbot
--- a/viperbot
+++ b/viperbot
@@ -71,9 +71,9 @@ viper_addtcl() {
 		case "${viper_script#*.}" in
 			"gz" )
 			    if [ ! `which gunzip` ]; then
-                                echo -e "\E[31mERROR: Your system doesn't have gunzip installed. This is required to uncompress a .gz file!\033[0m"
-                                exit $?
-                            fi
+                    echo -e "\E[31mERROR: Your system doesn't have gunzip installed. This is required to uncompress a .gz file!\033[0m"
+                    exit $?
+                fi
 			    gunzip $viper_dir/scripts/$viper_script
 			;;
 			"tar" | "tar.gz" )
@@ -81,8 +81,8 @@ viper_addtcl() {
 			;;
 			"zip" )
 			    if [ ! `which unzip` ]; then
-				echo -e "\E[31mERROR: Your system doesn't have unzip installed. This is required to uncompress a .zip file!\033[0m"
-				exit $?
+					echo -e "\E[31mERROR: Your system doesn't have unzip installed. This is required to uncompress a .zip file!\033[0m"
+					exit $?
 			    fi
 			    unzip $viper_dir/scripts/$viper_script
 			;;
@@ -199,16 +199,18 @@ viper_eggsetup(){
 viper_getbotnet(){
 	if [ -d $viper_dir ]; then
 		if [ ! -e $viper_dir/botnet.conf ]; then
-			echo -e "\E[33mNOTE: Be sure to edit $viper_dir/botnet.conf BEFORE adding your first bot.\033[0m"
-			echo -e "\E[33mYour first 2 bots that you add MUST match whats in the botnet.conf file.\033[0m"
-      			echo -e "\E[33mYour botnet bots should use IPv4 Addresses, This should allow them to link without issues.\033[0m"
-      			echo -e "\E[33mIf you need help with this please come see us at #servshells on Efnet or Freenode.\033[0m"
-			echo " "
-			read -p "Where is your botnet file? (eg: $viper_url/botnet.conf) " viperbotnet
-			viper_get $viperbotnet $viper_dir/botnet.conf
+			# Change: Will create botnet.conf dynamically based on user input
+			echo -en "Would you like to use your own botnet.conf? (y/n): "
+			read yesno;
+
+			if [[ $yesno = "y" || $yesno = "Y" ]]; then
+				read -p "Where is your botnet file? (eg: $viper_url/botnet.conf) " viperbotnet
+				viper_get $viperbotnet $viper_dir/botnet.conf
+			fi
 		fi
+
 		if [ ! -e $viper_dir/botnet.conf ]; then
-			viper_get $viper_url/botnet $viper_dir/botnet.conf
+			# Create botnet.conf
 		fi
 	fi
 }
